[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.jupyter-releaser]
skip = ["check-links", "publish-assets"]

[tool.jupyter-releaser.hooks]
after-draft-release = ["bash ./.github/scripts/bump_tag.sh"]

[tool.tbump.version]
current = "0.8.6"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
'''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "package.json"
