name: "Enforce Labels"
description: "Enforce assigning triage labels before merging PRs"
runs:
  using: "composite"
  steps:
    - name: sleep-if-needed
      shell: bash
      if: ${{ github.event.action == 'opened' }}
      run: sleep 60
    - name: enforce-triage-label
      uses: actions/github-script@v3
      with:
        script: |
          const required = ['bug', 'enhancement', 'feature', 'maintenance', 'documentation'];
          const issue = await github.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          let found = false;
          issue.labels.forEach(label => {
            if (required.includes(label)) {
              found = true;
            }
          });
          if (!found) {
            console.error('Select at least one triage label:')
            console.error(required)
            process.exit(1)
          }
