name: "Downstream Test"
description: "Test against a downstream library"
inputs:
  package_name:
    description: "The downstream package name"
    required: true
  package_spec:
    description: "The package spec(s) to install, defaults to '<package_name>[test]"
  pytest_args:
    description: "The pytest args (defaults to '--pyargs <package_name>'"
  env_values:
    description: "Optional env values to set for test, e.g. 'FOO=BAR FIZZ=BUZZ'"
runs:
  using: "composite"
  steps:
    - name: set up venv
      shell: bash
      run: |
          package_spec=${${{input.package_spec}}:-"${{inputs.package_name}}[test]"}
          pytest_args=${${{input.pytest_args}}:-"--pyargs ${{inputs.package_name}}"}
          python -m venv test
          ./test/bin/python -m pip install -U pip
          ./test/bin/python -m pip install ${package_spec}
          ./test/bin/python -m pip install . --force-reinstall
          ${{ input.env_values }}; ./test/bin/pytest ${pytest_args}
          rm -rf ./test
