name: Enforce PR label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: enforce-triage-label
        uses: ./.github/actions/enforce-label
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
