name: Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  check_downstream_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Base Setup
        uses: ./.github/actions/base-setup
      - name: Create a mock python package
        run:
          echo "from setuptools import setup; setup(name='foo')" > setup.py
      - name: Check Downstream test with defaults
        uses: ./.github/actions/downstream-test
        with:
          package_name: jupyter_client
      - name: Check Downstream test with overrides
        uses: ./.github/actions/downstream-test
        with:
          package_name: nbclient
          package_spec: "nbclient[test] ipykernel"
          test_command: "echo 'hello'"
          extra_test: "pytest --pyargs nbclient"
          env_values: IPYKERNEL_CELL_NAME=\<IPY-INPUT\>

  check_binder_link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Base Setup
        uses: ./.github/actions/base-setup
      - name: Check Binder Link
        uses: ./.github/actions/binder-link
        with:
          github_token: "FAKE"
          url_path: "/foo/bar"
