name: Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  downstream_defaults:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Base Setup
        uses: ./.github/actions/base-setup
      - name: Create a mock python package
        run:
          echo "from setuptools import setup; setup(name='foo')" > setup.py
      - name: Check Downstream test with defaults
        uses: ./.github/actions/downstream-test
        with:
          package_name: jupyter_client

  downstream_overrides:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Base Setup
        uses: ./.github/actions/base-setup
      - name: Create a mock python package
        run:
          echo "from setuptools import setup; setup(name='foo')" > setup.py
      - name: Check Downstream test with overrides
        uses: ./.github/actions/downstream-test
        with:
          package_name: nbclient
          package_spec: "nbclient[test] ipykernel"
          test_command: "echo 'hello'"
          extra_test: "pytest --pyargs nbclient"
          env_values: IPYKERNEL_CELL_NAME=\<IPY-INPUT\>

  binder_link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Base Setup
        uses: ./.github/actions/base-setup
      - name: Check Binder Link
        uses: ./.github/actions/binder-link
        with:
          github_token: "FAKE"
          url_path: "/foo/bar"

  pr_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Base Setup
      uses: ./.github/actions/base-setup
    - name: Check PR Script All Options
      uses: ./.github/actions/pr-script
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        script: "[\"jlpm run integrity\", \"jlpm run lint\"]"
        commit_message: "auto run cleanup"
        target:  "https://github.com/jupyterlab/maintainer-tools/pull/39"
        association: "MEMBER"
        git_username: "snuffy-bot"
        git_email: "snuffy-bot@example.com"
    - name: Check PR Script Defaults
      uses: ./.github/actions/pr-script
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        pre_commit: true
        commit_message: "auto run cleanup"
        target:  "https://github.com/jupyterlab/maintainer-tools/pull/39"
